### ISSUE TITLE
Problems using MariaDB

### ISSUE THREAD

**Issue by nonsenz** [fideloper/Vaprobash#225]
hi and thanks for vaprobash. 
i'm new to vaprobash and wanted to try it with mariadb instead of mysql. After including 

```
config.vm.provision "shell", path: "https://raw.github.com/#{github_username}/#{github_repo}/#{github_branch}/scripts/mariadb.sh", args: [mariadb_root_password, mariadb_version]
```

in the Vagrantfile and running vagrant up i receive the following error:

```
Setting up mariadb-server-10.0 (10.0.9+maria-1~precise) ...
 * Stopping MariaDB database server mysqld
   ...done.
dpkg: error processing mariadb-server-10.0 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mariadb-server:
 mariadb-server depends on mariadb-server-10.0 (= 10.0.9+maria-1~precise); however:
  Package mariadb-server-10.0 is not configured yet.
dpkg: error processing mariadb-server (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
No apport report written because the error message indicates its a followup error from a previous failure.
Errors were encountered while processing:
 mariadb-server-10.0
 mariadb-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

any idea whats wrong here? Have i missed something? I changed the syncing mode to rsync, but i don't see a connection:

```
 config.vm.synced_folder ".", "/vagrant",
      type: "rsync",
      rsync__exclude: ".git/",
      rsync__auto: true
```

**Comment by Battant** [comment]
Hello,

After upgrade from ubuntu 14.04 LTS to ubuntu 15,10, I get this error when I try to install mariadb

Failed to start mysql.service: Unit mysql.service failed to load: No such file or directory.
invoke-rc.d: initscript mysql, action "start" failed.
dpkg: error processing package mariadb-server-10.0 (--configure):
 subprocess installed post-installation script returned error exit status 6
dpkg: dependency problems prevent configuration of mariadb-server:
 mariadb-server depends on mariadb-server-10.0 (>= 10.0.23-0ubuntu0.15.10.1); however:
  Package mariadb-server-10.0 is not configured yet.

dpkg: error processing package mariadb-server (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                          Errors were encountered while processing:
 mariadb-server-10.0
 mariadb-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
mparchet@mparchet-W240EU-W250EUQ-W270EUQ:/media/mparchet/Sav_linux$ cleare
No command 'cleare' found, did you mean:
 Command 'clear' from package 'ncurses-bin' (main)
cleare: command not found
mparchet@mparchet-W240EU-W250EUQ-W270EUQ:/media/mparchet/Sav_linux$ clear

mparchet@mparchet-W240EU-W250EUQ-W270EUQ:/media/mparchet/Sav_linux$ sudo apt-get install mariadb-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mariadb-server is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up mariadb-server-10.0 (10.0.23-0ubuntu0.15.10.1) ...
Failed to stop mysql.service: Unit mysql.service not loaded.
invoke-rc.d: initscript mysql, action "stop" failed.
160411 12:38:32 [Note] /usr/sbin/mysqld (mysqld 10.0.23-MariaDB-0ubuntu0.15.10.1) starting as process 9262 ...
Failed to start mysql.service: Unit mysql.service failed to load: No such file or directory.
invoke-rc.d: initscript mysql, action "start" failed.
dpkg: error processing package mariadb-server-10.0 (--configure):
 subprocess installed post-installation script returned error exit status 6
dpkg: dependency problems prevent configuration of mariadb-server:
 mariadb-server depends on mariadb-server-10.0 (>= 10.0.23-0ubuntu0.15.10.1); however:
  Package mariadb-server-10.0 is not configured yet.

dpkg: error processing package mariadb-server (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                          Errors were encountered while processing:
 mariadb-server-10.0
 mariadb-server
E: Sub-process /usr/bin/dpkg returned an error code (1)


Could you help me please ?

Best regarda

Battant

**Comment by fideloper** [comment]
Howdy! 
Sorry for the delay, you might have resolved this already.

Things in vaprobash are only tested against 14.04. A lot of the repositories are specific to Ubuntu Trusty (14.04). 

MariaDB on 15.04/15.10 needs a different repository added. YOu can use their wizard to see the commands to run here:
https://downloads.mariadb.org/mariadb/repositories/#mirror=accretive&distro=Ubuntu&distro_release=wily--ubuntu_wily&version=10.1

Note that the `add-apt-repository` is adding a repository for "wily" instead of "trusty". These all go by the ubuntu release code names rather than a numeric release - Trusty for 14.04, Vivid for 15.04, Wily for 15.10.

**Comment by fideloper** [comment]
That was to @Battant, since I didn't mention you in previous response.

**Comment by silentvick** [comment]
Hello

Although I didn't use the Vaprobash, I had the same problem with MariaDB (10.0.24) in `ubuntu/trusty` box (came across this issue through google). Just wanted to share that I managed to resolve it just by switching to `phusion/ubuntu-14.04-amd64` box.
