### ISSUE TITLE
How to upgrade it to PHP 7?

### ISSUE THREAD

**Issue by mrgodhani** [fideloper/Vaprobash#537]
Hi

How would I upgrade my existing vagrant box to php 7?

**Comment by fideloper** [comment]
I haven't done this yet to see all the pitfalls, but if you're upgrading php5 to 7, you'll need to grab the [php -7 PPA (repository)](https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0):

```bash
sudo add-apt-repository 
ppa:ondrej/php-7.0 

sudo apt-get update

sudo apt-get install -y php6 php7-fpm # and perhaps the other php items: php7-mcrypt php7-pdo php6-mysql php7-gd ...
```

I'm not sure if that replaces php5 with php7. I believe service names are changed, so you'll hvae to do `sudo service php7-fpm [reload|restart|start|stop]` instead of using the `php5-fpm` service name.

**Comment by mrgodhani** [comment]
ye Tried to upgrade it. List of things won't work yet with php7 that is memcached etc.

**Comment by fideloper** [comment]
Thanks - I d'nt have a list personally, not sure what else might not be supported yet.

For memcached, if you're feeling adventurous, you should be able to build it yourself for php7:

http://stackoverflow.com/questions/33073141/has-anyone-got-memcached-to-work-on-laravel-homestead-php7-box

(You may need to install `php7-dev` first, and possibly the `build-essential` package)

**Comment by mikaelmattsson** [comment]
I made a simple fork for playing around with php7.0. I've tested it with nginx.
https://github.com/mikaelmattsson/Vaprobash-php7.0
