### ISSUE TITLE
Sequel Pro Remote ID Changed Error

### ISSUE THREAD

**Issue by dennisgaebel** [fideloper/Vaprobash#578]
I'm having a permissions issue I believe with Sequel Pro connecting using the setup guideline from the screenshot provided in the README. It has been quite some time since I've had to go through the setup procedure from scratch so I'm 100% sure I forgot to do a step or two, and in my case it looks like ssh issues? Could you help guide me on the procedures/steps I need to take so I can get my Vagrant machine to communicate with Sequel Pro? Appreciate the help 👍 🤘 

![Screenshot 2019-03-25 10 26 03](https://user-images.githubusercontent.com/13485205/54927363-6d060100-4ee8-11e9-913c-52db699bd933.png)
![Screenshot 2019-03-25 10 26 09](https://user-images.githubusercontent.com/13485205/54927366-70998800-4ee8-11e9-96c0-f651a129ece5.png)

**Comment by fideloper** [comment]
Hi!

It looks like since you have a new VM using the same IP address, your mac
isnt trusting it since part of SSH is to have a way to tell if a host has
changed when the same hostname/ipaddress is used.

To get around this, head (on your mac) to your ~/.ssh/known_hosts file and
delete the line with your VMs IP address before trying to startup the vm /
connecting using sequel pro again.

**Comment by dennisgaebel** [comment]
@fideloper Thanks for your help 🤘 Worked like a charm.
